### ISSUE TITLE
Mac OSX support

### ISSUE THREAD

**Issue by ciapamusche** [NotExpectedYet/s3d-thumbnail-generator#2]
is this plugin working with macOS ?

I did all the procedure installing everything by Brew but not thumbnails are generated
also command -crop doesn't exist.

Any advice?

Thanks...

**Comment by NotExpectedYet** [comment]
I don't have a Mac sorry. 

Check the other branch that's available though someone wrote a improved version if you haven't seen it already. That was suppose to be more cross platform.

**Comment by ciapamusche** [comment]
ok I've used other branch but there is a problem with screenshot. If I try to execute the command of the bash manually

It respond are not display in the stack.



May be the xdotool is not compatible with Mac

**Comment by NotExpectedYet** [comment]
Possibly, I had a similar issue with imagemagic on Windows with my personal setup. It's not supported there and couldn't figure out how to define the main screen.

All xdotools is used for in the script is to find the active screen and select that for use in the script. 

`"$(xdotool getwindowfocus -f)"` inside those quotations you should be able to provide a string but you'd have to look into the specifics of imagemagik and mac os to figure out what string is actually required. Hope that helps.

**Comment by boweeble** [comment]
I've just recently started using this software and wanted to use Simplify3D and have thumbnails so created this for Windows. Feel free to check it out here: https://github.com/boweeble/s3d-thumbnail-generator

**Comment by NotExpectedYet** [comment]
> I've just recently started using this software and wanted to use Simplify3D and have thumbnails so created this for Windows. Feel free to check it out here: https://github.com/boweeble/s3d-thumbnail-generator

Nice work! Could never get screenshots working on windows myself, glad someone figured it out.
