### ISSUE TITLE
Cannot get it to work

### ISSUE THREAD

**Issue by TheCableGuy99** [NotExpectedYet/s3d-thumbnail-generator#3]
Hi,

I'm really struggling with this, I've download it and it resides in:
/home/pi/s3d-thumbnail-generator

And thus the script is in:
/home/pi/s3d-thumbnail-generator/thumbnailGeneration.bash

I've set the working directory to:
/tmp

And in S3D I have:
curl -k -H "X-Api-Key: XXXXXXXXXXXXXXXXXXXXXXXX" -F "select=false" -F "print=false" -F "file=@[output_filepath]" "http://192.168.1.228:80/api/files/local" {STRIP "; postProcessing"}
/home/pi/s3d-thumbnail-generator/thumbnailGeneration.bash "[output_filepath]"

When I scan for files in the PrusaSlicer Thumbnail plugin it finds the gcode file but says there's no thumbnail.

Can you help please?

**Comment by TheCableGuy99** [comment]
Never mind, I realise now when you said it only works on Linux that you meant the slicer rather than Octoprint. I'll install it on a VM and see how it works from there.

**Comment by NotExpectedYet** [comment]
OctoPrint just needs the plugin working, I've not personally tried it in a while as I've moved over to SuperSlicer / Prusa Slicer for my slicing needs.

**Comment by NotExpectedYet** [comment]
Your script order would upload the file and then generate the script to by the looks? 

But yeah you'll need a GUI

**Comment by TheCableGuy99** [comment]
I’m going to try it with PrusaSlicer and your script in a Linux VM so hopefully i’ll find something that works and i like.

thanks!
